import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TrendingUp, TrendingDown, BarChart3 } from 'lucide-react';
export const AnalyticsTab = ({ analytics, isLoading }) => {
    if (isLoading) {
        return (_jsx("div", { className: "flex justify-center items-center h-32", children: _jsx("div", { className: "animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" }) }));
    }
    if (!analytics) {
        return (_jsx("div", { className: "bg-gray-50 p-6 rounded text-center text-gray-500", children: "Kh\u00F4ng c\u00F3 d\u1EEF li\u1EC7u th\u1ED1ng k\u00EA" }));
    }
    const { summary, by_category, units_breakdown } = analytics;
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsx("div", { className: "bg-green-50 p-6 rounded-lg border border-green-200", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "T\u1ED5ng thu nh\u1EADp" }), _jsxs("p", { className: "text-2xl font-bold text-green-600 mt-2", children: [summary.total_income.toLocaleString('vi-VN'), " VND"] })] }), _jsx(TrendingUp, { className: "text-green-600", size: 32 })] }) }), _jsx("div", { className: "bg-red-50 p-6 rounded-lg border border-red-200", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "T\u1ED5ng chi ph\u00ED" }), _jsxs("p", { className: "text-2xl font-bold text-red-600 mt-2", children: [summary.total_expense.toLocaleString('vi-VN'), " VND"] })] }), _jsx(TrendingDown, { className: "text-red-600", size: 32 })] }) }), _jsx("div", { className: "bg-blue-50 p-6 rounded-lg border border-blue-200", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "L\u1EE3i nhu\u1EADn r\u00F2ng" }), _jsxs("p", { className: `text-2xl font-bold mt-2 ${summary.net_profit >= 0 ? 'text-blue-600' : 'text-red-600'}`, children: [summary.net_profit.toLocaleString('vi-VN'), " VND"] })] }), _jsx(BarChart3, { className: "text-blue-600", size: 32 })] }) })] }), Object.keys(by_category).length > 0 && (_jsxs("div", { className: "bg-white border border-gray-200 rounded-lg p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Ph\u00E2n t\u00EDch theo danh m\u1EE5c" }), _jsx("div", { className: "space-y-3", children: Object.entries(by_category).map(([category, amount]) => {
                            const percentage = (Math.abs(amount) / (summary.total_income + summary.total_expense)) * 100 || 0;
                            return (_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between items-center mb-1", children: [_jsx("span", { className: "text-sm font-medium text-gray-700", children: category }), _jsxs("span", { className: `font-semibold ${amount >= 0 ? 'text-green-600' : 'text-red-600'}`, children: [amount.toLocaleString('vi-VN'), " VND"] })] }), _jsx("div", { className: "w-full bg-gray-200 rounded-full h-2", children: _jsx("div", { className: `h-2 rounded-full ${amount >= 0 ? 'bg-green-600' : 'bg-red-600'}`, style: { width: `${Math.min(percentage, 100)}%` } }) })] }, category));
                        }) })] })), units_breakdown && units_breakdown.length > 0 && (_jsxs("div", { className: "bg-white border border-gray-200 rounded-lg p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Ph\u00E2n t\u00EDch theo ph\u00F2ng" }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-gray-50 border-b border-gray-200", children: [_jsx("th", { className: "px-4 py-3 text-left text-sm font-semibold text-gray-700", children: "Ph\u00F2ng" }), _jsx("th", { className: "px-4 py-3 text-right text-sm font-semibold text-gray-700", children: "Thu nh\u1EADp" }), _jsx("th", { className: "px-4 py-3 text-right text-sm font-semibold text-gray-700", children: "Chi ph\u00ED" }), _jsx("th", { className: "px-4 py-3 text-right text-sm font-semibold text-gray-700", children: "L\u1EE3i nhu\u1EADn" })] }) }), _jsx("tbody", { children: units_breakdown.map((unit) => {
                                        const unitIncome = unit.income || 0;
                                        const unitExpense = unit.expense || 0;
                                        const unitProfit = unitIncome - unitExpense;
                                        return (_jsxs("tr", { className: "border-b border-gray-200 hover:bg-gray-50", children: [_jsx("td", { className: "px-4 py-3 text-sm font-medium text-gray-900", children: unit.name }), _jsxs("td", { className: "px-4 py-3 text-right text-sm text-green-600", children: [unitIncome.toLocaleString('vi-VN'), " VND"] }), _jsxs("td", { className: "px-4 py-3 text-right text-sm text-red-600", children: [unitExpense.toLocaleString('vi-VN'), " VND"] }), _jsxs("td", { className: `px-4 py-3 text-right text-sm font-semibold ${unitProfit >= 0 ? 'text-blue-600' : 'text-red-600'}`, children: [unitProfit.toLocaleString('vi-VN'), " VND"] })] }, unit.id));
                                    }) })] }) })] }))] }));
};
